name: Master Workflow

on:
    push:

jobs:
    version-matrix:
        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11']
        uses: ./.github/workflows/linting.yml # calls the one above ^
        with:
            python-version: ${{ matrix.python-version }}
        secrets: inherit
