name: Code Quality Testing
on: [push]
jobs:
    django_linting:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.9', '3.10', '3.11']
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: 'pip'
                  cache-dependency-path: |
                      requirements.txt
            - name: Install PIP dependencies, Apply Django migrate, and collectstatic
              run: |
                  .github/workflows/install_dependencies.sh
            - name: Analysing the code with RUFF and pycodestyle
              run: |
                  pylama .
                  ruff check

    django_migrations:
        runs-on: ubuntu-latest
        needs: django_linting
        strategy:
            matrix:
                python-version: ['3.9', '3.10', '3.11']
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: 'pip'
                  cache-dependency-path: |
                      requirements.txt
            - name: Install PIP dependencies, Apply Django migrate, and collectstatic
              run: |
                  .github/workflows/install_dependencies.sh
            - name: Check Django migrations
              run: |
                  python manage.py makemigrations --check
                  python manage.py migrate --check
                  python manage.py check
                  python manage.py check --database default
                  python manage.py check --deploy

    django_unit_testing:
        runs-on: ubuntu-latest
        needs: django_migrations
        strategy:
            matrix:
                python-version: ['3.9', '3.10', '3.11']
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: 'pip'
                  cache-dependency-path: |
                      requirements.txt
            - name: Install PIP dependencies, Apply Django migrate, and collectstatic
              run: |
                  .github/workflows/install_dependencies.sh
            - name: Run Django tests
              run: |
                  python manage.py test
