name: Code Quality Testing
on: [push]
jobs:
    django_linting:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.9', '3.10', '3.11']
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: build
              uses: ./.github/actions/build

            - name: Analysing the code with RUFF and pycodestyle
              run: |
                  source venv/bin/activate
                  pylama .
                  ruff check

            - name: Check Django migrations
              run: |
                  source venv/bin/activate
                  python manage.py makemigrations --check
                  python manage.py migrate --check
                  python manage.py check
                  python manage.py check --database default
                  python manage.py check --deploy

            - name: Run Django tests
              run: |
                  source venv/bin/activate
                  python manage.py test
