name: Code Quality Testing

on:
    workflow_call:
        inputs:
            # the variable you can use in place of a matrix
            python-version:
                required: true
                type: string

jobs:
    django_linting:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: build
              uses: ./.github/actions/build

            - name: Analysing the code with RUFF and pycodestyle
              run: |
                  source venv/bin/activate
                  pylama .
                  ruff check

    django_migrations:
        runs-on: ubuntu-latest
        needs: django_linting
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: build
              uses: ./.github/actions/build

            - name: Check Django migrations
              run: |
                  echo "Inputs python version: ${{ inputs.python-version }}"
                  echo "Matrix version: ${{ matrix.version }}"
                  echo "Matrix python version: ${{ matrix.python-version }}"
                  source venv/bin/activate
                  python manage.py makemigrations --check
                  python manage.py migrate --check
                  python manage.py check
                  python manage.py check --database default
                  python manage.py check --deploy

    django_tests:
        runs-on: ubuntu-latest
        needs: django_migrations
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: build
              uses: ./.github/actions/build

            - name: Run Django tests
              run: |
                  source venv/bin/activate
                  python manage.py test
