name: Code Quality Testing
on: [push]
jobs:
    django_linting:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.9', '3.10', '3.11']
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: 'pip'
                  cache-dependency-path: |
                      requirements.txt
            - name: Install PIP dependencies, Apply Django migrate, and collectstatic
              run: |
                  .github/workflows/install_dependencies.sh

            - name: Analysing the code with RUFF and pycodestyle
              run: |
                  pylama .
                  ruff check

            - name: Check Django migrations
              run: |
                  python manage.py makemigrations --check
                  python manage.py migrate --check
                  python manage.py check
                  python manage.py check --database default
                  python manage.py check --deploy

            - name: Run Django tests
              run: |
                  python manage.py test
