name: Linting, Migrations, and Testing

on:
    workflow_call:
        inputs:
            # the variable you can use in place of a matrix
            python-version:
                required: true
                type: string

jobs:
    Django-Linting:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: build
              uses: ./.github/actions/build
              with:
                  python-version: ${{ inputs.python-version }}

            - name: Analysing the code with RUFF and pycodestyle
              run: |
                  source venv/bin/activate
                  pylama .
                  ruff check

    Django-Migrations:
        runs-on: ubuntu-latest
        needs: Django-Linting
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: build
              uses: ./.github/actions/build
              with:
                  python-version: ${{ inputs.python-version }}

            - name: Check Django migrations
              run: |
                  source venv/bin/activate
                  python manage.py makemigrations --check
                  python manage.py migrate --check
                  python manage.py check
                  python manage.py check --database default
                  python manage.py check --deploy

    Django-Tests:
        runs-on: ubuntu-latest
        needs: Django-Migrations
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: build
              uses: ./.github/actions/build
              with:
                  python-version: ${{ inputs.python-version }}

            - name: Run Django tests
              run: |
                  source venv/bin/activate
                  python -m coverage run manage.py test
                  coverage xml
                  coverage html

            - name: Coveralls
              uses: coverallsapp/github-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: coverage.xml
                  flag-name: run-${{ join(inputs.*, '-') }}
                  parallel: true

    Cypress-Test:
        runs-on: ubuntu-latest
        needs: Django-Migrations
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: build
              uses: ./.github/actions/build
              with:
                  python-version: ${{ inputs.python-version }}

            - name: Run Cypress Test
              uses: cypress-io/github-action@v6
              with:
                  command: python3 manage.py testserver cypress/fixtures/testdb.json --no-input & npx cypress run --headless
